# Generated by Django 5.2.5 on 2025-08-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Informacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('paragrafo', models.TextField()),
                ('imagem', models.ImageField(upload_to='historia/')),
            ],
            options={
                'verbose_name_plural': 'Informações',
            },
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('idade', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('posicao', models.CharField(max_length=50)),
                ('local_nascimento', models.CharField(max_length=100)),
                ('altura', models.CharField(max_length=10)),
                ('gols', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('imagem', models.ImageField(upload_to='jogadores/')),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campeonato', models.CharField(max_length=50)),
                ('rodada', models.CharField(max_length=50)),
                ('estadio', models.CharField(max_length=50)),
                ('data_hora', models.CharField(max_length=50)),
                ('logo_casa', models.ImageField(upload_to='logos/')),
                ('logo_fora', models.ImageField(upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('subtitulo', models.CharField(max_length=50)),
                ('texto', models.TextField()),
                ('imagem', models.ImageField(upload_to='noticias/')),
            ],
        ),
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('conteudo', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Elementos do Sobre',
            },
        ),
    ]
