# Generated by Django 5.2.5 on 2025-08-16 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0002_alter_jogador_options_noticia_categoria_noticia_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='idade',
            field=models.CharField(max_length=7),
        ),
    ]
